package igor.kuridza.ferit.hr.najboljiucenik.common

const val DB_NAME = "NajboljiUcenikDB"
const val PREFS_NAME = "NajboljiUcenikPref"
const val PREFS_TIME_KEY = "PrefsTime"
//dialogs tags
const val NEW_MATH_QUESTION_TAG = "NEW_MATH_QUESTION"
const val EDIT_MATH_QUESTION_TAG = "EDIT_MATH_QUESTION"
const val NEW_TRUE_FALSE_QUESTION_TAG = "NEW_TRUE_FALSE_QUESTION"
const val EDIT_TRUE_FALSE_QUESTION_TAG = "EDIT_TRUE_FALSE_QUESTION"
const val NEW_PROVERB_QUESTION_TAG = "NEW_PROVERB_QUESTION"
const val EDIT_PROVERB_QUESTION_TAG = "EDIT_PROVERB_QUESTION"
//
const val CATEGORY_TYPE_KEY = "CATEGORY_TYPE"
const val MATH_SUBJECT = "MATH"
const val GEOGRAPHY_SUBJECT = "GEOGRAPHY"
const val CROATIAN_SUBJECT = "CROATIAN"
const val SUBJECT_KEY = "SUBJECT"
const val PLAYER1_SCORE_KEY = "PLAYER1_SCORE"
const val PLAYER2_SCORE_KEY = "PLAYER2_SCORE"
const val SCORE_KEY = "SCORE"

const val ADDITION_SUBTRACTION = "ADDITION_SUBTRACTION"
const val DIVISION_MULTIPLICATION = "DIVISION_MULTIPLICATION"

const val MATH_COLLECTION_PATH = "MATH"
const val FLAGS_DOCUMENT_PATH = "FLAGS"
const val TRUE_FALSE_COLLECTION_PATH = "TRUE_FALSE"
const val PROVERBS_PATH = "PROVERBS"

const val CROATIAN_TRUE_FALSE = "CROATIAN_TRUE_FALSE"
const val CROATIAN_PROVERB = "CROATIAN_PROVERB"
const val GEOGRAPHY_TRUE_FALSE = "GEOGRAPHY_TRUE_FALSE"
const val GEOGRAPHY_FLAGS = "GEOGRAPHY_FLAGS"
const val PLAYERS_SCORE_PATH = "PLAYERS"



